std_msgs/Header header
uint16 counter 
uint64 sample_time
string utc_time
float64 eulerangles_roll
float64 eulerangles_pitch
float64 eulerangles_yaw
float64 gyro_x
float64 gyro_y
float64 gyro_z
float64 acc_x
float64 acc_y
float64 acc_z
float64 accfree_x
float64 accfree_y
float64 accfree_z
float64 mag_x
float64 mag_y
float64 mag_z
float64 delta_q0
float64 delta_q1
float64 delta_q2
float64 delta_q3
float64 vel_x
float64 vel_y
float64 vel_z
float64 latitude
float64 longitude
float64 altitude
float32 temperature

string status_words




